ws_health_exporter role was added
paritytech/ansible-galaxy pull request #32
Opened 2023-05-18 08:18 UTC by kogeler

2023-05-18 11:46 UTC, aardbol requested changes

2023-05-18 11:46 UTC, aardbol commented on roles/ws_health_exporter/molecule/default/group_vars/all.yml
> +node_binary_version: "v0.9.40"
You're not basing it on the version, like you did in other roles?

2023-05-18 11:46 UTC, aardbol commented on roles/ws_health_exporter/molecule/default/molecule.yml
> +    image: "paritytech/debian10:latest"
Shouldn't this be debian 11 now?

2023-05-18 11:57 UTC, aardbol commented on roles/ws_health_exporter/templates/.service.j2
> +Group={{ ws_health_exporter_user}}
Will this var work? Missing space in` {{ ws_health_exporter_user}}`

2023-05-19 11:17 UTC, kogeler commented on roles/ws_health_exporter/molecule/default/molecule.yml
> +    image: "paritytech/debian10:latest"
fixed

2023-05-19 11:24 UTC, aardbol commented on roles/ws_health_exporter/molecule/default/molecule.yml
> +    image: "paritytech/debian10:latest"
looking goooood

2023-05-19 11:29 UTC, aardbol approved these changes
lgtm

2023-05-21 09:32 UTC, BulatSaif commented on roles/ws_health_exporter/tasks/main.yml
> +      state: absent
It is better to remove this step, this is "new" role and git history is empty,  this step may confuse new users.

2023-05-21 09:36 UTC, BulatSaif approved these changes
Good job, small cleanup needed

2023-05-21 09:36 UTC, BulatSaif commented on roles/ws_health_exporter/tasks/main.yml
> +    tags: ['ws-health-exporter-test1']
```suggestion
```

2023-05-21 09:36 UTC, BulatSaif commented on roles/ws_health_exporter/vars/main.yml
> +_ws_health_exporter_old_file: "/home/{{ ws_health_exporter_user }}/bin/{{ _ws_health_exporter_name }}.py"
```suggestion
```

2023-05-21 09:37 UTC, BulatSaif commented on roles/ws_health_exporter/tasks/main.yml
> +      state: absent
```suggestion
```

It is better to remove this step, this is "new" role and git history is empty,  this step may confuse new users.

2023-05-21 09:38 UTC, BulatSaif approved these changes

2023-05-22 14:56 UTC, merged